export const CREATE_CUSTOMER = 'createCustomer'
export const REMOVE_CUSTOMER = 'removeCustomer'
export const UPDATE_CUSTOMER = 'updateCustomer'
export const GET_CUSTOMER = 'getCustomer'
export const GET_CUSTOMERS = 'getCustomers'

export const CREATE_PRODUCT = 'createProduct'
export const REMOVE_PRODUCT = 'removeProduct'
export const UPDATE_PRODUCT = 'updateProduct'
export const GET_PRODUCT = 'getProduct'
export const GET_PRODUCTS = 'getProducts'
export const GET_PRODUCTS_BY_SUPPLIER = 'getProductsBySupplier'

export const CREATE_SUPPLIER = 'createSupplier'
export const REMOVE_SUPPLIER = 'removeSupplier'
export const UPDATE_SUPPLIER = 'updateSupplier'
export const GET_SUPPLIER = 'getSupplier'
export const GET_SUPPLIERS = 'getSuppliers'

export const CREATE_PURCHASE_ORDER = 'createPurchaseOrder'
export const CLOSE_PURCHASE_ORDER = 'closePurchaseOrder'
export const UPDATE_PURCHASE_ORDER = 'updatePurchaseOrder'
export const GET_PURCHASE_ORDER = 'getPurchaseOrder'
export const GET_PURCHASE_ORDERS = 'getPurchaseOrders'
export const APPROVE_PURCHASE_ORDER = 'approvePurchaseOrder'
export const IN_TRANSIT_PURCHASE_ORDER = 'inTransitPurchaseOrder'
export const PIER_TO_WAREHOUSE_PURCHASE_ORDER = 'pierToWarehousePurchaseOrder'
export const ARRIVAL_PURCHASE_ORDER = 'arrivalPurchaseOrder'
export const GET_PURCHASE_ORDER_LOGS = 'getPurchaseOrderLogs'

export const CREATE_SALES_ORDER = 'createSalesOrder'
export const REMOVE_SALES_ORDER = 'removeSalesOrder'
export const UPDATE_SALES_ORDER = 'updateSalesOrder'
export const GET_SALES_ORDER = 'getSalesOrder'
export const GET_SALES_ORDERS = 'getSalesOrders'

export const SET_ERRORS = 'setErrors'
